include_guard(DIRECTORY)

set(CMAKE_CXX_STANDARD_LIBRARIES "")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/scripts")
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 23)
