include_guard(DIRECTORY)

macro(set_parent)
  foreach(arg ${ARGN})
    set(${arg} ${${arg}} PARENT_SCOPE)
  endforeach()
endmacro()

function(include_items name folder)
  set(LIST_SRCS ${ARGN})
  string(REGEX REPLACE "^\/|\/$" "" folder ${folder})
  set(folder "${CMAKE_CURRENT_SOURCE_DIR}/${folder}")
  list(TRANSFORM LIST_SRCS PREPEND "${folder}/")
  set(${name} "${LIST_SRCS}" PARENT_SCOPE)
endfunction()

macro(list_get ls idx out)
  list(GET ${ls} ${idx} ${out})
endmacro(list_get)

function(list_get_or ls idx alt out)
  list(LENGTH ${ls} _LIST_LEN)
  if(${idx} LESS _LIST_LEN)
    list_get(${ls} ${idx} _LIST_OUT)
  else()
    set(_LIST_OUT ${alt})
  endif()
  set(${out} ${_LIST_OUT} PARENT_SCOPE)
endfunction(list_get_or)
